---
title: "Eligibility and take up of housing benefits"
author: "Michael Škvrňák"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(dplyr)
library(haven)
library(Hmisc)
library(ggplot2)
library(targets)
library(MatchIt)

tar_load(r_silc_2023)

r_silc_2023 <- r_silc_2023 %>% 
  mutate(country = as.character(country))

if_na <- function(x, replace = 0){
  if_else(is.na(x), replace, x)
}

calculate_dimensions <- function(df){
  df %>% 
    mutate(
      dim_affordability = housing_overburden,
      dim_insecurity = arrears_mortgage_rent %in% c("Yes, once", "Yes, twice or more") |
          arrears_utility %in% c("Yes, once", "Yes, twice or more"),
      dim_quality = case_when(
        is.na(overcrowded_eurostat) ~ NA,
        TRUE ~ (overcrowded_eurostat |
          ability_to_keep_warm == "No"),
      ),
      dim_quality2 = case_when(
        is.na(overcrowded_eurostat) ~ NA,
        TRUE ~ (overcrowded_eurostat |
                  ability_to_keep_warm == "No" |
                  bath_shower %in% c("No", "Yes, shared") |
                  toilet %in% c("No", "Yes, shared") |
                  leaks_damp == "Yes"),
      ),
      dim_locality =
        probs_noise == "Yes" |
          probs_crime == "Yes" |
          probs_pollution == "Yes",
    )
}


```

## Czechia
```{r}
cz_2023 <- r_silc_2023 %>% 
  filter(country == "CZ")

CZ_EXCHANGE_RATE <- 1 / 24.564

eligibility_cz_2023 <- cz_2023 %>% 
  mutate(
    income_disposable_wo_housing = income_disposable - allowance_housing,
    r_rent = if_na(rent, 0),
    r_mortgage = if_na(mortgage_principal_payment, 0),
    main_energy_source = as_factor(main_energy_source),
    urbanisation = as_factor(urbanisation),
    prague = as.character(region) == "CZ01",
    month_income = (income_disposable - allowance_housing) / 12,
    normative_costs = case_when(
      # Tenants + Prague
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & prague & n_persons == 1 ~ 
        10121 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & prague & n_persons == 2 ~ 
        13629 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & prague & n_persons == 3 ~ 
        18312 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & prague & n_persons >= 4 ~ 
        22495 * CZ_EXCHANGE_RATE,
      # Tenants + > 100 tis.
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Cities (DB010>=2021), Densely populated area (EE,LV:1,2=1) (DB010<2021)" &
        n_persons == 1 ~ 
        8271 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Cities (DB010>=2021), Densely populated area (EE,LV:1,2=1) (DB010<2021)" &
        n_persons == 2 ~ 
        11097 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Cities (DB010>=2021), Densely populated area (EE,LV:1,2=1) (DB010<2021)" &
        n_persons == 3 ~ 
        15000 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Cities (DB010>=2021), Densely populated area (EE,LV:1,2=1) (DB010<2021)" &
        n_persons >= 4 ~ 
        18502 * CZ_EXCHANGE_RATE,
      # Tenants + > 50 tis.
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Towns and suburbs (MT:2,3=2) (DB010>=2021), Intermediate area (MT:2,3=2) (DB010<2021)" &
        n_persons == 1 ~ 
        7935 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Towns and suburbs (MT:2,3=2) (DB010>=2021), Intermediate area (MT:2,3=2) (DB010<2021)" &
        n_persons == 2 ~ 
        10637 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Towns and suburbs (MT:2,3=2) (DB010>=2021), Intermediate area (MT:2,3=2) (DB010<2021)" &
        n_persons == 3 ~ 
        14399 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Towns and suburbs (MT:2,3=2) (DB010>=2021), Intermediate area (MT:2,3=2) (DB010<2021)" &
        n_persons >= 4 ~ 
        17777 * CZ_EXCHANGE_RATE,
      # Tenants + < 49.
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Rural areas (DB010>=2021), Thinly populated area (DB010<2021)" &
        n_persons == 1 ~ 
        6929 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Rural areas (DB010>=2021), Thinly populated area (DB010<2021)" &
        n_persons == 2 ~ 
        9261 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Rural areas (DB010>=2021), Thinly populated area (DB010<2021)" &
        n_persons == 3 ~ 
        12599 * CZ_EXCHANGE_RATE,
      tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & 
        urbanisation == "Rural areas (DB010>=2021), Thinly populated area (DB010<2021)" &
        n_persons >= 4 ~ 
        15606 * CZ_EXCHANGE_RATE, 
      
      # Owners
      !tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & n_persons == 1 ~ 
        6232 * CZ_EXCHANGE_RATE,
      !tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & n_persons == 2 ~ 
        8432 * CZ_EXCHANGE_RATE,
      !tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & n_persons == 3 ~ 
        11561 * CZ_EXCHANGE_RATE,
      !tenure_status %in% c("Tenant, rent at market price", "Tenant, rent at reduced price", 
                           "Tenant, rent free") & n_persons >= 4 ~ 
        14368 * CZ_EXCHANGE_RATE
      
    ), 
    eligible_housing_costs = (total_housing_cost - r_mortgage) %>% 
      if_else(. < normative_costs, ., normative_costs), 
    share_costs_to_income = eligible_housing_costs / month_income,
    eligibility_allowance_housing = case_when(
      prague & share_costs_to_income >= 0.35 ~ eligible_housing_costs - 0.35 * month_income, 
      !prague & share_costs_to_income >= 0.3 ~ eligible_housing_costs - 0.3 * month_income, 
      TRUE ~ 0
    )
  ) %>% calculate_dimensions() %>% 
  group_by(hh_id) %>% 
  slice(1) %>% 
  ungroup()

m_out <- matchit(takeup_allowance_housing ~ n_persons + 
                   income_disposable_wo_housing + 
                   eligibility_allowance_housing + 
                   region + tenure_status, 
        # exact = ~ country + tenure_status, 
        method = "nearest",
        distance = "mahalanobis",
        replace = TRUE,
        exact = ~ n_persons +  
          tenure_status + region,
        data = eligibility_cz_2023 %>% 
          filter(!is.na(region)))

summary(m_out)
png("paper/figs/cze-covars.png", width = 640)
plot(summary(m_out))
dev.off()

m_data <- match_data(m_out) %>% 
  mutate(takeup_allowance_housing = factor(takeup_allowance_housing, 
                                               levels = c(FALSE, TRUE), 
                                               labels = c("No, not taking benefits",
                                                          "Yes, taking benefits")), 
         eligibility_allowance_housing = eligibility_allowance_housing / 10)

## Matched data
m1_aff <- glm(dim_affordability ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data)

m1_aff %>% 
  modelsummary::modelsummary(., stars = TRUE)

m1_qual <- glm(dim_quality ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data) 

m1_qual %>% 
  modelsummary::modelsummary(., stars = TRUE)

glm(dim_quality2 ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data) %>% 
  modelsummary::modelsummary(., stars = TRUE)

glm(dim_insecurity ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data) %>% 
  modelsummary::modelsummary(., stars = TRUE)

glm(dim_locality ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data) %>% 
  modelsummary::modelsummary(., stars = TRUE)

modelsummary::modelplot(m1_aff, exponentiate = TRUE,
                        coef_map = c(
                          "eligibility_allowance_housing"="Housing benefits eligibility (amount, 10 EUR)",
                          "takeup_allowance_housingYes, taking benefits"="Yes, taking benefits")) + 
  scale_x_log10() + 
  xlab("Odds ratios and 95% CI") + 
  geom_vline(xintercept = 1) + 
  ggtitle("Effect of housing benefits on unaffordability")

ggsave("paper/figs/fig_effect_affordability.png", width = 8, height = 6, bg = "white")
  

modelsummary::modelplot(m1_qual, exponentiate = TRUE,
                        coef_map = c(
                          "eligibility_allowance_housing"="Housing benefits eligibility (amount, 10 EUR)",
                          "takeup_allowance_housingYes, taking benefits"="Yes, taking benefits")) + 
  scale_x_log10() + 
  xlab("Odds ratios and 95% CI") + 
  geom_vline(xintercept = 1) + 
  ggtitle("Effect of housing benefits on quality")

ggsave("paper/figs/fig_effect_quality.png", width = 8, height = 6, bg = "white")
# ggeffects::ggeffect(m1_aff, terms = c("takeup_allowance_housing")) %>% 
#   plot()


glm(dim_quality ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data) %>% 
  modelsummary::modelsummary(., stars = TRUE)
glm(overcrowded_eurostat ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data) %>% 
  modelsummary::modelsummary(., stars = TRUE)

glm(ability_to_keep_warm ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data |> mutate(ability_to_keep_warm = as.numeric(ability_to_keep_warm == "Yes"))) %>% 
  modelsummary::modelsummary(., stars = TRUE)


glm(dim_insecurity ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data)

cz_affordability <- glm(dim_affordability ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data)

cz_insecurity <- glm(dim_insecurity ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data)

cz_arrears_mortgage_rent <- glm(arrears_mortgage_rent ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data |> 
      mutate(arrears_mortgage_rent = as.numeric(arrears_mortgage_rent %in% c("Yes, once", "Yes, twice or more"))))

cz_arrears_utility <- glm(arrears_mortgage_rent ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data |> 
      mutate(arrears_utility = as.numeric(arrears_utility %in% c("Yes, once", "Yes, twice or more"))))

cz_quality <- glm(dim_quality ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data)

cz_overcrowded <- glm(overcrowded_eurostat ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data)
cz_warm <- glm(ability_to_keep_warm ~ takeup_allowance_housing + eligibility_allowance_housing + 
      income_disposable_wo_housing, 
    family = "binomial",
    data = m_data |> mutate(ability_to_keep_warm = as.numeric(ability_to_keep_warm == "Yes")))

pr2 <- data.frame(
  label = "pseudo-R2",
  x1 = pscl::pR2(cz_affordability)["McFadden"], 
  x2 = pscl::pR2(cz_insecurity)["McFadden"],
  x3 = pscl::pR2(cz_quality)["McFadden"],
  x4 = pscl::pR2(cz_arrears_mortgage_rent)["McFadden"],
  x5 = pscl::pR2(cz_arrears_utility)["McFadden"],
  x6 = pscl::pR2(cz_overcrowded)["McFadden"],
  x7 = pscl::pR2(cz_warm)["McFadden"]
)

modelsummary::modelsummary(
  list(
    "Unaffordability" = cz_affordability, 
    "Insecurity" = cz_insecurity, 
    "Poor quality" = cz_quality, 
    "Arrears on mortgage/rent" = cz_arrears_mortgage_rent, 
    "Arrears on utilities" = cz_arrears_utility, 
    "Overcrowded" = cz_overcrowded, 
    "Unable to keep warm" = cz_warm
  ), 
  stars = TRUE, 
  fmt = 2,
  coef_rename = c(
    "takeup_allowance_housingYes, taking benefits"="Taking benefits", 
    "eligibility_allowance_housing" = "amount of benefits eligible for",
    "income_disposable_wo_housing" = "disposable income without benefits"
  ), 
  gof_map = "nobs", 
  add_rows = pr2
)

```

## Finland
```{r}
fi_2023 <- r_silc_2023 %>% 
  filter(country == "FI")

pensioners_fi_2023 <- fi_2023 %>% 
  filter(econ_status == "Retired")

pensioners_hb_2023 <- pensioners_fi_2023 %>% 
  mutate(
    r_rent = if_na(rent, 0),
    heating_cost_categories = case_when(
      region %in% c("FI1B", "FI1C") ~ 1,
      region == "FI19" ~ 2,
      region == "FI1D" ~ 3
    ),
    renovated = as_factor(renovated_in_past_5_years) %in% c(
      "Yes - three or more", "Yes - two measures", "Yes - one measure"),
    max_eligible_square_area = 70 + (n_persons - 1) * 15,
    eligible_square_area = if_else(dwelling_size_m2 > max_eligible_square_area,
                                  max_eligible_square_area, dwelling_size_m2),
    # TODO: increase if house built before 1974
    eligible_heating_costs = case_when(
      heating_cost_categories == 1 ~ 1.32 * eligible_square_area,
      heating_cost_categories == 2 ~ 1.45 * eligible_square_area,
      heating_cost_categories == 3 ~ 1.60 * eligible_square_area
    ),
    # TODO: increase if house built before 1974
    maintenance_charge = if_else(
      tenure_status %in% c("Owner without outstanding mortgage",
                           "Owner with outstanding mortgage"), 
      44.37 * n_persons, 
      0
    ),
    eligible_water_costs = n_persons * 29.81,
    eligible_housing_costs = r_rent + eligible_heating_costs + maintenance_charge + 
      eligible_water_costs, 
    maximum_housing_costs = case_when(
      region == "FI1B" ~ 8613/12, 
      TRUE ~ (7912+6949)/2/12
    ), 
    income_limit = case_when(
      n_persons == 1 ~ 9534, 
      TRUE ~ 15565
    ),
    person_net_income = rowSums(across(starts_with("person_net")), na.rm = TRUE),
    own_responsibility = (631.94 + 0.413 * (person_net_income - income_limit))/12, 
    eligibility_allowance_housing = (0.85 * (eligible_housing_costs-own_responsibility)) %>% 
      if_else(. < 0, 0, .)
  ) %>% 
  select(
    person_net_income, rent, eligible_housing_costs, 
    eligibility_allowance_housing, allowance_housing, everything()
  )

fi_pensioners_hb <- matchit(takeup_allowance_housing ~ n_persons + 
                              income_disposable_eqi + 
                              eligibility_allowance_housing + 
                              region + tenure_status, 
        # exact = ~ country + tenure_status, 
        method = "nearest",
        distance = "mahalanobis",
        replace = TRUE,
        exact = ~ n_persons +  
          tenure_status + region,
        data = pensioners_hb_2023 %>% 
          filter(!is.na(region)))

summary(fi_pensioners_hb)
plot(summary(fi_pensioners_hb))

fi_pensionsers_hb_data <- match_data(fi_pensioners_hb) %>% 
  calculate_dimensions()

glm(dim_affordability ~ takeup_allowance_housing + eligibility_allowance_housing, 
    family = "binomial",
    data = fi_pensionsers_hb_data) %>% 
  modelsummary::modelsummary(., stars = TRUE)

glm(dim_quality ~ takeup_allowance_housing + eligibility_allowance_housing, 
    family = "binomial",
    data = fi_pensionsers_hb_data) %>% 
  modelsummary::modelsummary(., stars = TRUE)

glm(dim_quality2 ~ takeup_allowance_housing + eligibility_allowance_housing, 
    family = "binomial",
    data = fi_pensionsers_hb_data) %>% 
  modelsummary::modelsummary(., stars = TRUE)

glm(dim_insecurity ~ takeup_allowance_housing + eligibility_allowance_housing, 
    family = "binomial",
    data = fi_pensionsers_hb_data) %>% 
  modelsummary::modelsummary(., stars = TRUE)

glm(dim_locality ~ takeup_allowance_housing + eligibility_allowance_housing, 
    family = "binomial",
    data = fi_pensionsers_hb_data) %>% 
  modelsummary::modelsummary(., stars = TRUE)
```

```{r}
fi_general_hb_2023 <- fi_2023 %>% 
  group_by(hh_id) %>% 
  mutate(any_pensioner = any(econ_status == "Retired"), 
         n_adults = sum(age >= 18), 
         n_old_age = sum(age >= 65),
         n_children = sum(age < 18)
    ) %>% 
  slice(1) %>% 
  filter(!any_pensioner) %>% 
  ungroup()

nrow(fi_general_hb_2023)

fi_allowance_2023 <- fi_general_hb_2023 %>% 
  mutate(
    maximum_housing_costs = case_when(
      region == "FI1B" & n_persons == 1 ~ (537+520)/2,
      region == "FI1B" & n_persons == 2 ~ (778+746)/2,
      region == "FI1B" & n_persons == 3 ~ (990+941)/2,
      region == "FI1B" & n_persons == 4 ~ (1157+1097)/2,
      region == "FI1B" & n_persons > 4 ~ (1157+1097)/2 + 
        ((144+137)/2 * (n_persons-4)),
      region != "FI1B" & n_persons == 1 ~ (413+364)/2,
      region != "FI1B" & n_persons == 2 ~ (602+530)/2,
      region != "FI1B" & n_persons == 3 ~ (764+678)/2,
      region != "FI1B" & n_persons == 4 ~ (906+808)/2,
      region != "FI1B" & n_persons > 4 ~ (906+808)/2 + 
        ((124+119)/2 * (n_persons-4)),
    ),
    eligible_heating_costs = if_else(
      region == "FI1D", 
      42 + 14 * (n_persons - 1) * 1.06,
      42 + 14 * (n_persons - 1)
    ),
    r_rent = if_na(rent, 0),
    maintenance_charge = case_when(
      tenure_status %in% c("Owner without outstanding mortgage",
                           "Owner with outstanding mortgage") & 
        dwelling_type == "Detached house" &
        region == "FI1D" &
        n_persons == 1 ~ 99 * 1.06,
      tenure_status %in% c("Owner without outstanding mortgage",
                           "Owner with outstanding mortgage") & 
        dwelling_type == "Detached house" &
        n_persons == 1 ~ 99,
      tenure_status %in% c("Owner without outstanding mortgage",
                           "Owner with outstanding mortgage") & 
        dwelling_type == "Detached house" &
        region == "FI1D" &
        n_persons == 2 ~ 119 * 1.06,
      tenure_status %in% c("Owner without outstanding mortgage",
                           "Owner with outstanding mortgage") & 
        dwelling_type == "Detached house" &
        n_persons == 2 ~ 119,
      tenure_status %in% c("Owner without outstanding mortgage",
                           "Owner with outstanding mortgage") & 
        dwelling_type == "Detached house" &
        region == "FI1D" &
        n_persons == 3 ~ 150 * 1.06,
      tenure_status %in% c("Owner without outstanding mortgage",
                           "Owner with outstanding mortgage") & 
        dwelling_type == "Detached house" &
        n_persons == 3 ~ 150,
      tenure_status %in% c("Owner without outstanding mortgage",
                           "Owner with outstanding mortgage") & 
        dwelling_type == "Detached house" &
        region == "FI1D" &
        n_persons >= 4 ~ (177 + (55 * (n_persons - 4))) * 1.06,
      tenure_status %in% c("Owner without outstanding mortgage",
                           "Owner with outstanding mortgage") & 
        dwelling_type == "Detached house" &
        n_persons == 4 ~ (177 + (55 * (n_persons - 4))),
      TRUE ~ 0
    ),
    eligible_water_costs = n_persons * 19,
    # TODO: 73% of monthly interest
    interest_payment = 0,
    max_maintenance_charge = 
      if_else(
        maintenance_charge / (maintenance_charge + 
                                eligible_heating_costs +
                                eligible_water_costs + interest_payment) > 0.3,
        (eligible_heating_costs + eligible_water_costs + interest_payment) / 0.7 - 
          (eligible_heating_costs + eligible_water_costs + interest_payment), 
        maintenance_charge
      ),
    acceptable_housing_costs = r_rent + eligible_heating_costs + 
        maintenance_charge + eligible_water_costs,
    eligible_gross_income = income_gross - allowance_family - 
      allowance_social - allowance_housing,
    basic_deductible = 0.42 * (eligible_gross_income/12 - (619 + 103 * n_adults + 
                                 228 * n_children)),
    eligibility_allowance_housing = (0.8 * (acceptable_housing_costs - basic_deductible)) %>% 
      if_else(. < 0, 0, .)
  ) %>% 
  select(
    tenure_status, rent, n_persons,
    eligibility_allowance_housing, allowance_housing,
    eligible_gross_income, everything()
  )

fi_allowance_2023_match <- matchit(takeup_allowance_housing ~ n_persons + 
                              income_disposable_eqi + 
                              eligibility_allowance_housing + 
                              region + tenure_status, 
        # exact = ~ country + tenure_status, 
        method = "nearest",
        distance = "mahalanobis",
        replace = TRUE,
        exact = ~ n_persons +  
          tenure_status + region,
        data = fi_allowance_2023 %>% 
          filter(!is.na(region)))

summary(fi_allowance_2023_match)
plot(summary(fi_allowance_2023_match))

fi_allowance_2023_match_df <- match_data(fi_allowance_2023_match) %>% 
  calculate_dimensions() %>% 
  mutate(takeup_allowance_housing = factor(takeup_allowance_housing, 
                                               levels = c(FALSE, TRUE), 
                                               labels = c("No, not taking benefits",
                                                          "Yes, taking benefits")), 
         eligibility_allowance_housing = eligibility_allowance_housing / 10)

m2_aff <- glm(dim_affordability ~ takeup_allowance_housing +
                eligibility_allowance_housing, 
    family = "binomial",
    data = fi_allowance_2023_match_df)

m2_aff %>% 
  modelsummary::modelsummary(., stars = TRUE)

modelsummary::modelplot(m2_aff, exponentiate = TRUE,
                        coef_map = c(
                          "eligibility_allowance_housing"="Housing benefits eligibility (amount, 10 EUR)",
                          "takeup_allowance_housingYes, taking benefits"="Yes, taking benefits")) + 
  scale_x_log10() + 
  xlab("Odds ratios and 95% CI") + 
  geom_vline(xintercept = 1) + 
  ggtitle("Effect of housing benefits on unaffordability")

ggsave("figs/fig_effect_affordability_finland.png", width = 8, height = 6, bg = "white")

ggsave("figs/fig_effect_quality.png", width = 8, height = 6, bg = "white")

m2_qual <- glm(dim_quality ~ takeup_allowance_housing + eligibility_allowance_housing, 
    family = "binomial",
    data = fi_allowance_2023_match_df) 

m2_qual %>% 
  modelsummary::modelsummary(., stars = TRUE)

# glm(dim_quality2 ~ takeup_allowance_housing + eligibility_allowance_housing, 
#     family = "binomial",
#     data = fi_allowance_2023_match_df) %>% 
#   modelsummary::modelsummary(., stars = TRUE)

modelsummary::modelplot(m2_qual, exponentiate = TRUE,
                        coef_map = c(
                          "eligibility_allowance_housing"="Housing benefits eligibility (amount, 10 EUR)",
                          "takeup_allowance_housingYes, taking benefits"="Yes, taking benefits")) + 
  scale_x_log10() + 
  xlab("Odds ratios and 95% CI") + 
  geom_vline(xintercept = 1) + 
  ggtitle("Effect of housing benefits on quality")

m2_ins <- glm(dim_insecurity ~ takeup_allowance_housing + eligibility_allowance_housing, 
    family = "binomial",
    data = fi_allowance_2023_match_df) 

m2_ins %>% 
  modelsummary::modelsummary(., stars = TRUE)

modelsummary::modelplot(m2_ins, exponentiate = TRUE,
                        coef_map = c(
                          "eligibility_allowance_housing"="Housing benefits eligibility (amount, 10 EUR)",
                          "takeup_allowance_housingYes, taking benefits"="Yes, taking benefits")) + 
  scale_x_log10() + 
  xlab("Odds ratios and 95% CI") + 
  geom_vline(xintercept = 1) + 
  ggtitle("Effect of housing benefits on insecurity")

ggsave("figs/fig2_effect_insecurity_finland.png", width = 8, height = 6, bg = "white")

glm(dim_locality ~ takeup_allowance_housing + eligibility_allowance_housing, 
    family = "binomial",
    data = fi_allowance_2023_match_df) %>% 
  modelsummary::modelsummary(., stars = TRUE)

glm(ability_to_keep_warm ~ takeup_allowance_housing + eligibility_allowance_housing, 
    family = "binomial",
    data = fi_allowance_2023_match_df %>% 
      mutate(ability_to_keep_warm == "Yes")) %>% 
  modelsummary::modelsummary(., stars = TRUE)



```



## Austria
```{r, eval=FALSE}
at_2023 <- r_silc_2023 %>% 
  filter(country == "AT")
```


## Netherlands
```{r, eval=FALSE}
# https://euromod-web.jrc.ec.europa.eu/sites/default/files/2025-04/Y15_CR_NL_final.pdf
nl_2023 <- r_silc_2023 %>% 
  filter(country == "NL")

NL_PENSION_AGE <- 67

nl_2023 %>% 
  select(tenure_status, rent, total_housing_cost, allowance_housing) %>% 
  head()

recode_nan_share <- function(x){
  case_when(
    !is.nan(x) ~ x,
    n_pension_age == 0 ~ 0, 
    n_pension_age == n_persons ~ 1
  )
}

r_nl_2023 <- nl_2023 %>% 
  mutate(
    person_net_income = rowSums(across(
      c(person_net_cash_income, person_net_selfemployed_income, 
        person_net_unemployment_benefits, person_net_oldage_benefits, 
        person_net_survivor_benefits, person_net_sickness_benefits, 
        person_net_disability_benefits, person_net_education_benefits)
    ), na.rm = TRUE), 
    r_rent = if_na(rent, 0),
    is_pensioner = age >= NL_PENSION_AGE
  ) %>% 
  group_by(hh_id) %>% 
  mutate(
    hh_income = sum(person_net_income),
    n_pension_age = sum(age >= NL_PENSION_AGE), 
    income_pensioners_share = 
      case_when(
        hh_income != 0 ~ sum(person_net_income * is_pensioner) / hh_income, 
        n_pension_age == 0 ~ 0, 
        n_pension_age == n_persons ~ 1
      )
  ) %>% 
  select(
    is_pensioner, income_pensioners_share, person_net_income, everything()
  ) %>% 
  mutate(
    household_type = case_when(
      n_persons == 1 & n_pension_age == 0 ~ "A",
      n_persons > 1 & income_pensioners_share < 0.5 ~ "C",
      n_persons == 1 & n_pension_age == 1 ~ "E",
      n_persons > 1 & income_pensioners_share >= 0.5 ~ "G"
    ),
    norm_rent = case_when(
      household_type == "A" ~ 5.96879E-07 * income_disposable ^ 2 + 
        0.002363459 * income_disposable + 16.94,
      household_type == "C" ~ x,
      household_type == "E" ~ x,
      household_type == "G" ~ x,
    ),
    housing_allowance_eligibility = case_when(
      tenure_status %in% c("Owner without outstanding mortgage", "Owner with outstanding mortgage", 
                           "Tenant, rent free") ~ 0,
      
    )
  )

# TODO: Asset test (Asset test: no rent subsidy is paid if tax payable on income in Box 3 is nonzero.)
# The general tax free asset allowance is €30,846 per person.
table(r_nl_2023$household_type, useNA = "always")
  
r_nl_2023 %>% 
  filter(is.na(household_type)) %>%
  select(is_pensioner, n_persons, n_pension_age) %>% 
  View()
  tab(household_type)

View()

nl_2023 %>% 
  group_by(hh_id) %>% 
  mutate(
    
  ) %>% 
  mutate(
    household_type = case_when(
      n_persons == 1 & n_pension_age == 0 ~ "A",
      n_persons > 1 & income_pensioners_share < 0.5 ~ "C",
      n_persons == 1 & n_pension_age == 1 ~ "E",
      n_persons > 1 & income_pensioners_share >= 0.5 ~ "G"
    )
  ) %>% 
  select(
    r_rent, household_type
  )
  
```

