---
title: "Validations"
author: "Michael Škvrňák"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(targets)
library(validate)

tar_load(validation_silc_2023)
tar_load(starts_with("validation"))
```

```{r}
plot(validation_silc_2007)
summary(validation_silc_2007)

plot(validation_silc_2008)
summary(validation_silc_2008)

plot(validation_silc_2009)
summary(validation_silc_2009)

plot(validation_silc_2010)
summary(validation_silc_2010)

plot(validation_silc_2011)
summary(validation_silc_2011)

plot(validation_silc_2012)
summary(validation_silc_2012)

plot(validation_silc_2013)
summary(validation_silc_2013)

plot(validation_silc_2014)
summary(validation_silc_2014)

plot(validation_silc_2015)
summary(validation_silc_2015)

plot(validation_silc_2016)
summary(validation_silc_2016)

plot(validation_silc_2017)
summary(validation_silc_2017)

plot(validation_silc_2018)
summary(validation_silc_2018)

plot(validation_silc_2019)
summary(validation_silc_2019)

plot(validation_silc_2020)
summary(validation_silc_2020)

plot(validation_silc_2021)
summary(validation_silc_2021)

plot(validation_silc_2022)
summary(validation_silc_2022)

plot(validation_silc_2023)
summary(validation_silc_2023)
```
### Panel data
```{r}
plot(validation_silc_2023_panel)
summary(validation_silc_2023_panel)
```

